### ISSUE TITLE
[建议] 仓库结构优化和程序性能改进

### ISSUE THREAD

**Issue by BiDuang** [MerakW/AppStore_Notify#1]
问安！可以为此项目添加 `.gitignore` 文件以使git在同步仓库时忽略无用的本地构建文件（例如`__pycache__`等）。

另外，还可以将网络请求库 `requests` 和数据库交互库进行异步优化以获得更好的性能。

对于 `requests` ，我认为可以使用 `aiohttp` 库来异步优化。对于数据库，我暂时只用过 MySQL 的解决方案，你可以尝试搜索 SQLite 的异步方案。

祝好！

**Comment by MerakW** [comment]
谢谢BiDuang 我在后续的更新中调整和优化这些功能，感谢你的意见
